@startuml
'https://plantuml.com/sequence-diagram

autonumber

FinalUser -> RegistrationController: Call to /changePassword
RegistrationController -> UserService: Get the user by email
UserService -> UserRepository: Get the user by email
UserRepository -> RegistrationController: Return the user
RegistrationController -> UserService: Check if the old password matches with the actual password
UserService -> RegistrationController: The old password matches with the actual password
RegistrationController -> UserService: Change the actual password for the new password
UserService -> UserRepository: Encode and update the actual password for the new password
RegistrationController -> FinalUser: Password has been changed successfully
@enduml