@startuml
'https://plantuml.com/sequence-diagram

autonumber
group Get token for reset password
FinalUser -> RegistrationController: Call to /resetPassword
RegistrationController -> UserService: Get the user by email
UserService -> UserRepository: Get the user by email
UserRepository -> UserService: Return the user
UserService -> RegistrationController: Return the user
RegistrationController -> RegistrationController: Generate a token
RegistrationController -> UserService: Create a new PasswordResetToken
UserService -> PasswordResetTokenRepository: Create a new PasswordResetToken
RegistrationController -> FinalUser: Show the link to reset password with a token
end
group URL confirmation and change of password
FinalUser -> RegistrationController: Call to /savePassword
RegistrationController -> UserService: Check if PasswordResetToken exists
UserService -> PasswordResetTokenRepository: Get the PasswordResetToken by token
UserService -> RegistrationController: PasswordResetToken exists
RegistrationController -> UserService:Change the password
UserService -> UserRepository:Encode and update the new password
end
@enduml